name: finview_lite
description: A Flutter investment insights dashboard
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fl_chart: ^0.66.0
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  provider: ^6.1.1
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/portfolio.json
    - assets/logos/
